-- MySQL Script generated by MySQL Workbench
-- Mon Aug 28 14:51:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_e_de_todos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_e_de_todos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_e_de_todos` DEFAULT CHARACTER SET utf8 ;
USE `db_e_de_todos` ;

-- -----------------------------------------------------
-- Table `tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ensino` VARCHAR(45) NOT NULL,
  `assunto` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `foto` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tb_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_cursos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(50) NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `duracao` TIME NOT NULL,
  `instrutor` VARCHAR(35) NOT NULL,
  `descricao` TEXT NULL,
  `pre_requisitos` VARCHAR(300) NULL,
  `avaliacao` VARCHAR(300) NULL,
  `foto` VARCHAR(100) NULL,
  `categoria_id` BIGINT NULL,
  `usuario_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_cursos_tb_categoria_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_tb_cursos_tb_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_cursos_tb_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `tb_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_cursos_tb_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
